[config]
schemaVersion = "0.1.0"

[package]
namespace = "Binbin"
name = "Graendor"
versionNumber = "0.1.0"
description = "Hero Mod for Graendor, the Icebreaker. ..."
websiteUrl = "https://github.com/binbinmods/Graendor"
containsNsfwContent = false

[package.dependencies]
meds-Obeliskial_Essentials = "1.5.1"
meds-Obeliskial_Content = "1.7.2"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./Graendor"
target = ""


[publish]
repository = "https://thunderstore.io"
communities = [ "across-the-obelisk", ]
[publish.categories]
across-the-obelisk = [ "mods", ]


